Exit with a non-zero exit code if there is a lint framework error.
Summary:
`arc lint` requires that the linter exit 0 to function properly; we
support that with the `--always-exit-0` flag.  But `arc lint` says you
should exit non-zero if you want the linter run to fail: that is, if
you want to say you were unable to lint.

We do have certain errors of that type in runlint.py, so now we fail
in that case.  We do this by separating out the concept of lint errors
from framework errors.

Before this change, we were silently passing `arc lint` when
runlint.py itself was running into trouble.

Test Plan:
First, I verified normal lint operation didn't change: In webapp,
modified javascript/shared-package/location-model.js to say
`toDateString();` on the last line, and then ran

    % ka-lint --always-exit-0 --blacklist=yes --propose-arc-fixes 'javascript/shared-package/location-model.js'
    javascript/shared-package/location-model.js:42:1: Eno-undef "toDateString" is not defined.
    javascript/shared-package/location-model.js:42: E314 Using U.S.-specific date formatting. Use intl.i18n.format_date() and friends instead. (intl.i18n_lint.lint_strftime)
    % echo $?
    0

Then I verified errors did cause badness by making two modifications:

1. modifying khan-linter's eslintrc to add an extra comma at the end
of `"browser": true`
2. adding this line to the end of linters.Eslint.process_files():
   `raise ValueError('oops')`

I then ran:

    % ka-lint --always-exit-0 --blacklist=yes --propose-arc-fixes 'javascript/shared-package/location-model.js'
    javascript/shared-package/location-model.js:42:1: Eno-undef "toDateString" is not defined.
    ERROR linting ['javascript/shared-package/location-model.js']: oops
    ERROR running the extra linter /home/csilvers/khan/webapp/tools/runlint.py on these files: ['/home/csilvers/khan/webapp/javascript/shared-package/location-model.js']: Traceback (most recent call last):
      File "/home/csilvers/khan/webapp/tools/runlint.py", line 232, in <module>
        errors = run_lint(linter_files, files_to_lint, args.verbose)
      File "/home/csilvers/khan/webapp/tools/runlint.py", line 148, in run_lint
        for error in fn(files_to_lint):
      File "/home/csilvers/khan/webapp/handlebars/handlebars_lint.py", line 43, in lint_javascript_in_handlebars
        errors = jinja2_lint.run_eslint(lint_inputs)
      File "/home/csilvers/khan/webapp/jinja2_lint.py", line 126, in run_eslint
        eslint_config = json.loads(eslintrc_contents)
      File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
        return _default_decoder.decode(s)
      File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
        obj, end = self.scan_once(s, idx)
    ValueError: Expecting property name: line 194 column 5 (char 5324)
    % echo $?
    2

Reviewers: john, mroth

Reviewed By: mroth

Differential Revision: https://phabricator.khanacademy.org/D23521