Report ESLint error offsets in bytes, not characters
Summary:
It turns out that the `arc lint` autofixer expects error offsets to be specified in bytes, not characters. However, ESLint reports error offsets in characters, not bytes. This can cause `arc lint` to suggest Prettier insertions/removals at the wrong offset, because the line contained UTF-8 characters.

In this change, we update our custom ESLint error reporter plugin to report byte offsets instead of character offsets. The ESLint reporter already has the file's source loaded into memory, so we can just examine the line ourselves, encode it to UTF-8, and count the number of bytes until the character mentioned in the error.

We also fix an independent UTF-8 bug, in which the linter crashes when suggesting removals on lines that contain non-ASCII characters.

Test Plan:
Temporarily update webapp's `.eslintrc` to enable Prettier.

Run `arc lint javascript/components/schedule-package/ui/schedule-ui.jsx.fixture.js`.

Before this change, you would receive suggestions like the following, inserting code into the wrong place:

```
   Error  (S&RX) Eprettier/prettier
    Insert ` (`

              25 });
              26
              27 export const instances = [
    >>> -     28     fixture("Calendar view: Aug–Sep 2017 (mobile-sized wrapper)", () =>
        +            fixture("Calendar view: Aug–Sep 2017 (mobile-sized wrapper)", ()  (=>
              29         <div className={css(styles.wrapper, styles.wrapperMobile)}>
              30             <ScheduleUI
              31                 dateConfigs={mockDateConfigs}
              32                 today={moment("2017-08-01")}
```

After this change, you now receive suggestions like the following, inserting code into the right place:

```
   Error  (S&RX) Eprettier/prettier
    Insert ` (`

              25 });
              26
              27 export const instances = [
    >>> -     28     fixture("Calendar view: Aug–Sep 2017 (mobile-sized wrapper)", () =>
        +            fixture("Calendar view: Aug–Sep 2017 (mobile-sized wrapper)", () => (
              29         <div className={css(styles.wrapper, styles.wrapperMobile)}>
              30             <ScheduleUI
              31                 dateConfigs={mockDateConfigs}
              32                 today={moment("2017-08-01")}
```

Additionally, edit one of the `dateConfigs={}` lines to instead say `dateConfigs={"💩" + mockDateConfigs    }`. (This creates extra whitespace, which Prettier will want to remove, on a line that contains a wide emoji character.)

Before this change, the linter would crash, because `bad_line` was an encoded UTF-8 `str`, but `to_remove` was a decoded `unicode` object:

```
Traceback (most recent call last):
  File "/Users/matt/khan/devtools/khan-linter/bin/ka-lint", line 760, in <module>
    options.verbose, options.propose_arc_fixes)
  File "/Users/matt/khan/devtools/khan-linter/bin/ka-lint", line 678, in main
    num_new_errors = lint_processor.process_files(files)
  File "/Users/matt/khan/devtools/khan-linter/linters.py", line 659, in process_files
    num_errors += self.process(filename, contents, lintlines)
  File "/Users/matt/khan/devtools/khan-linter/linters.py", line 578, in process
    contents_lines)
  File "/Users/matt/khan/devtools/khan-linter/linters.py", line 570, in _process_one_line
    six.print_(self._maybe_add_arc_fix(output_line, bad_line))
  File "/Users/matt/khan/devtools/khan-linter/linters.py", line 507, in _maybe_add_arc_fix
    self._clean_prettier_string(remove.group(1)), '')
  File "/Users/matt/khan/devtools/khan-linter/lint_util.py", line 75, in add_arc_fix_str
    new_col = bad_line.find(to_remove, col)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 30: ordinal not in range(128)
```

After this change, you now receive suggestions like the following:

```
   Error  (S&RX) Eprettier/prettier
    Delete `    `

              37     fixture("Calendar view: Aug–Sep 2017 (desktop-sized wrapper)", () =>
              38         <div className={css(styles.wrapper, styles.wrapperDesktop)}>
              39             <ScheduleUI
    >>> -     40                 dateConfigs={"💩" + mockDateConfigs    }
        +                        dateConfigs={"💩" + mockDateConfigs}
              41                 today={moment("2017-08-01")}
              42                 visibleRange={[moment("2017-08-05"), moment("2017-09-21")]}
              43             />
              44         </div>,
```

Additionally, try some other simple error cases (like using an undeclared variable), and confirm that `arc lint` still points to the correct offset.

Finally, I'm about to run the Prettier bulk-upgrade tool I'm working on, which uses `arc lint` to auto-apply Prettier to all JS files. (More details coming soon!) If things still work after that, that'll be pretty good evidence that this approach generalizes well.

Reviewers: csilvers, john, kevinb

Reviewed By: csilvers

Differential Revision: https://phabricator.khanacademy.org/D41128