Explicitly depend on graphql
When deploying, I saw the following error on Jenkins:

```
Traceback (most recent call last):
  File "/home/ubuntu/webapp-workspace/webapp/testing/lint_test.py", line 62, in test
    self.run_lint([dirname])
  File "/home/ubuntu/webapp-workspace/webapp/testing/lint_test.py", line 89, in run_lint
    '%d LINT ERRORS:\n%s' % (num_errors, f.getvalue()))
AssertionError: 1 LINT ERRORS:
ERROR:root:ERROR linting ['content_editing/tools/calculate_perseus_version.js', 'content_editing/tools/find_graphie_images_in_items.js', 'content_editing/tools/list_perseus_widgets.js'] with <class 'linters.Eslint'>:
Traceback (most recent call last):
  File "/home/ubuntu/webapp-workspace/webapp/../devtools/khan-linter/runlint.py", line 720, in main
    num_new_errors = lint_processor.process_files(files)
  File "/home/ubuntu/webapp-workspace/webapp/../devtools/khan-linter/linters.py", line 629, in process_files
    file_to_lint_output = self.lint_files(files)
  File "/home/ubuntu/webapp-workspace/webapp/../devtools/khan-linter/linters.py", line 604, in lint_files
    stdout_lines.extend(self._run_eslint(files[i:i + 2000]))
  File "/home/ubuntu/webapp-workspace/webapp/../devtools/khan-linter/linters.py", line 571, in _run_eslint
    % (process.returncode, stderr, stdout))
RuntimeError: Unexpected stderr from linter (exited 2):
Error: Cannot find module 'graphql'
Referenced from: /home/ubuntu/webapp-workspace/webapp/.eslintrc
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ubuntu/webapp-workspace/devtools/khan-linter/node_modules/eslint-plugin-graphql/lib/index.js:18:16)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

This is an attempt to fix that.

Auditors: john

Test Plan:
```
ka-lint javascript/content-library-package/modules/mappers.jsx
```